const DBKEY='qavrin_real_v1';let db=readDB(),session=localStorage.getItem(DBKEY+'_session');
const seeds=[
['Ishita Sharma','ishita07','Education','Is our education system preparing us for real life?','We memorise for exams, not for understanding. We compete for marks, not for growth.\n\nIt is time we rethink what success really means.',1200],
['Raghav Mehta','raghavwrites','Society','We need better spaces for disagreement.','A healthy debate is not about winning. It is about leaving the conversation with a better understanding of the other side.',730],
['Mehak Verma','mehakwrites','Campus','What should colleges teach that textbooks do not?','Money, communication, basic law, digital safety and critical thinking should not be optional life lessons.',482],
['Arjun Nair','arjunn','Careers','Your first job is not your final identity.','We put too much pressure on young people to choose one path at 20. Careers change. Skills compound. Learning should matter more than a perfect first decision.',341]
];
function readDB(){try{return JSON.parse(localStorage.getItem(DBKEY))||{users:[],posts:[],follows:[],notifications:[]}}catch{return{users:[],posts:[],follows:[],notifications:[]}}}
if(!db.posts.length)db.posts=seeds.map((s,i)=>({id:'seed'+i,userId:'seed'+i,name:s[0],username:s[1],topic:s[2],title:s[3],body:s[4],likes:s[5],likedBy:[],savedBy:[],comments:[],createdAt:Date.now()-i*7200000,tags:[s[2].toLowerCase()]}));
if(!db.users.length)db.users=[{id:'demo',name:'Demo User',username:'demo_user',email:'demo@qavrin.in',password:'qavrin123',bio:'Here to read, think and write.'}];
if(!db.follows)db.follows=[];if(!db.notifications)db.notifications=[];saveDB();
function saveDB(){localStorage.setItem(DBKEY,JSON.stringify(db))}
function me(){return db.users.find(u=>u.id===session)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function initials(n='Q'){return n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function ago(t){const m=Math.max(1,Math.floor((Date.now()-t)/60000));return m<60?m+'m':m<1440?Math.floor(m/60)+'h':Math.floor(m/1440)+'d'}
function toast(msg){toastBox.textContent=msg;toastBox.classList.remove('hidden');setTimeout(()=>toastBox.classList.add('hidden'),1800)}
const toastBox=document.getElementById('toast');
function openModal(id){document.getElementById(id).classList.remove('hidden')}
function closeModal(id){document.getElementById(id).classList.add('hidden')}
function currentUser(){return me()}
function renderIdentity(){const u=currentUser();if(!u)return;sideName.textContent=u.name;sideUser.textContent='@'+u.username;sideInitial.textContent=initials(u.name);profileInitial.textContent=initials(u.name);profileName.textContent=u.name;profileHandle.textContent='@'+u.username;profileBio.textContent=u.bio||'Your voice. Your perspective.';statPosts.textContent=db.posts.filter(p=>p.userId===u.id).length;statFollowers.textContent=db.follows.filter(f=>f.to===u.id).length;statFollowing.textContent=db.follows.filter(f=>f.from===u.id).length}
function getPosts(){let a=[...db.posts],q=searchInput.value.trim().toLowerCase(),topic=topicFilter.value,sort=document.querySelector('.feedTab.active')?.dataset.sort||'latest';if(q)a=a.filter(p=>(p.title+' '+p.body+' '+p.name+' '+p.username+' '+p.tags.join(' ')).toLowerCase().includes(q));if(topic!=='all')a=a.filter(p=>p.topic===topic);if(sort==='popular')a.sort((a,b)=>b.likes-a.likes);else if(sort==='following'){const ids=db.follows.filter(f=>f.from===currentUser()?.id).map(f=>f.to);a=a.filter(p=>ids.includes(p.userId))}else a.sort((a,b)=>b.createdAt-a.createdAt);return a}
function postHTML(p){const u=currentUser();const liked=!!u&&p.likedBy.includes(u.id),saved=!!u&&p.savedBy.includes(u.id);return `<article class="post" data-id="${p.id}"><div class="postHead"><div class="author"><div class="initial">${esc(initials(p.name))}</div><div><strong>${esc(p.name)}</strong><span>@${esc(p.username)} · ${ago(p.createdAt)}</span></div></div><span class="topic">${esc(p.topic)}</span></div><h3>${esc(p.title)}</h3><div class="postBody">${esc(p.body)}</div><div class="tags">${p.tags.map(t=>`<span>#${esc(t)}</span>`).join('')}</div><div class="actions"><button class="action ${liked?'active':''}" data-action="like">♥ ${p.likes}</button><button class="action" data-action="comment">◯ ${p.comments.length}</button><button class="action ${saved?'active':''}" data-action="save">◇ ${saved?'Saved':'Save'}</button>${p.userId===u?.id?'<button class="action" data-action="delete">Delete</button>':''}</div><div class="commentBox"><input id="comment-${p.id}" placeholder="Add a comment"><button data-action="send">Send</button></div>${p.comments.slice(-3).map(c=>`<div class="comment"><b>${esc(c.name)}</b> · ${esc(c.text)}</div>`).join('')}</article>`}
function render(target='feed',list=getPosts()){document.getElementById(target).innerHTML=list.length?list.map(postHTML).join(''):`<div class="railCard"><b>No thoughts found.</b><p>Be the first person to start a conversation.</p></div>`}
function switchView(view){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById(view).classList.remove('hidden');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const t={home:['YOUR FEED','Thoughts worth reading.'],explore:['EXPLORE','Find a conversation.'],notifications:['NOTIFICATIONS','Stay in the loop.'],saved:['SAVED','Things worth revisiting.'],profile:['PROFILE','Your QAVRIN.']}[view];eyebrow.textContent=t[0];pageTitle.textContent=t[1];if(view==='home')render();if(view==='explore')renderExplore();if(view==='notifications')renderNotifications();if(view==='saved')render('savedFeed',db.posts.filter(p=>p.savedBy.includes(currentUser()?.id)));if(view==='profile')render('profileFeed',db.posts.filter(p=>p.userId===currentUser()?.id));sidebar.classList.remove('open')}
function renderExplore(){const counts={};db.posts.forEach(p=>counts[p.topic]=(counts[p.topic]||0)+1);topicGrid.innerHTML=['India','Education','Careers','Campus','Technology','Society','Debates','General'].map(t=>`<button class="topicTile" data-topic-tile="${t}"><b>${t}</b><span>${counts[t]||0} conversations</span></button>`).join('');render('exploreFeed',[...db.posts].sort((a,b)=>b.likes-a.likes))}
function renderNotifications(){const u=currentUser();const list=db.notifications.filter(n=>n.to===u?.id);notificationList.innerHTML=(list.length?list:[{text:'Welcome to QAVRIN. Start your first conversation.',time:'now'}]).map(n=>`<div class="railCard"><b>${esc(n.text)}</b><p>${esc(n.time||'now')}</p></div>`).join('')}
function openComposer(){currentUser()?openModal('composerModal'):openModal('authModal')}
function login(e){e.preventDefault();const u=db.users.find(x=>x.email===loginEmail.value.trim().toLowerCase()&&x.password===loginPassword.value);if(!u)return toast('Incorrect email or password.');session=u.id;localStorage.setItem(DBKEY+'_session',session);closeModal('authModal');renderIdentity();toast('Welcome back.')}
function signup(e){e.preventDefault();const email=signupEmail.value.trim().toLowerCase(),username=signupUsername.value.trim().toLowerCase();if(db.users.some(x=>x.email===email))return toast('Email already registered.');if(db.users.some(x=>x.username===username))return toast('Username already taken.');const u={id:crypto.randomUUID(),name:signupName.value.trim(),username,email,password:signupPassword.value,bio:''};db.users.push(u);session=u.id;localStorage.setItem(DBKEY+'_session',session);saveDB();closeModal('authModal');renderIdentity();toast('Account created.')}
function demo(){session='demo';localStorage.setItem(DBKEY+'_session',session);closeModal('authModal');renderIdentity();toast('Signed in.')}
function publish(e){e.preventDefault();const u=currentUser();if(!u)return openModal('authModal');const tags=postTags.value.split(',').map(x=>x.trim().replace(/^#/,'')).filter(Boolean).slice(0,6);db.posts.unshift({id:crypto.randomUUID(),userId:u.id,name:u.name,username:u.username,topic:postTopic.value,title:postTitle.value.trim(),body:postBody.value.trim(),tags,likes:0,likedBy:[],savedBy:[],comments:[],createdAt:Date.now()});saveDB();e.target.reset();charCount.textContent='0 / 2000';closeModal('composerModal');render();toast('Published.')}
function handlePost(e){const action=e.target.closest('[data-action]')?.dataset.action,card=e.target.closest('.post');if(!card||!action)return;const p=db.posts.find(x=>x.id===card.dataset.id),u=currentUser();if(!u)return openModal('authModal');if(action==='like'){const i=p.likedBy.indexOf(u.id);if(i<0){p.likedBy.push(u.id);p.likes++}else{p.likedBy.splice(i,1);p.likes--}}if(action==='save'){const i=p.savedBy.indexOf(u.id);if(i<0)p.savedBy.push(u.id);else p.savedBy.splice(i,1)}if(action==='delete'){if(p.userId!==u.id)return;db.posts=db.posts.filter(x=>x.id!==p.id)}if(action==='send'){const input=document.getElementById('comment-'+p.id),text=input.value.trim();if(text){p.comments.push({name:u.name,text});input.value=''}}saveDB();render();toast(action==='send'?'Comment added.':action==='delete'?'Deleted.':action==='save'?(p.savedBy.includes(u.id)?'Saved.':'Removed from saved.'):'')}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>switchView(n.dataset.view));document.querySelectorAll('.discover button').forEach(b=>b.onclick=()=>{topicFilter.value=b.dataset.topic;switchView('home');render()});document.getElementById('writeBtn').onclick=openComposer;document.getElementById('heroWrite').onclick=openComposer;
document.querySelectorAll('.feedTab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.feedTab').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});searchInput.oninput=()=>render();topicFilter.onchange=()=>render();postBody.oninput=()=>charCount.textContent=postBody.value.length+' / 2000';
document.getElementById('postForm').onsubmit=publish;document.getElementById('loginForm').onsubmit=login;document.getElementById('signupForm').onsubmit=signup;document.getElementById('demoBtn').onclick=demo;document.getElementById('profile').querySelector('#editProfileBtn').onclick=()=>{const u=currentUser();editName.value=u.name;editBio.value=u.bio||'';openModal('editModal')};
document.getElementById('editForm').onsubmit=e=>{e.preventDefault();const u=currentUser();u.name=editName.value.trim();u.bio=editBio.value.trim();saveDB();renderIdentity();closeModal('editModal');toast('Profile updated.')};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.getElementById('feed').onclick=handlePost;document.getElementById('exploreFeed').onclick=handlePost;document.getElementById('savedFeed').onclick=handlePost;document.getElementById('profileFeed').onclick=handlePost;
document.getElementById('exploreSearch').oninput=e=>{const q=e.target.value.toLowerCase();render('exploreFeed',db.posts.filter(p=>(p.title+' '+p.body+' '+p.name+' '+p.tags.join(' ')).toLowerCase().includes(q)))};
document.getElementById('topicGrid').onclick=e=>{const t=e.target.closest('[data-topic-tile]')?.dataset.topicTile;if(t){topicFilter.value=t;switchView('home');render()}};document.getElementById('menuBtn').onclick=()=>sidebar.classList.toggle('open');
document.querySelectorAll('.authTab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.authTab').forEach(x=>x.classList.remove('active'));t.classList.add('active');loginForm.classList.toggle('hidden',t.dataset.auth!=='login');signupForm.classList.toggle('hidden',t.dataset.auth!=='signup')});
renderIdentity();render();
