const KEY="qavrin-local-v4";let db=load();let session=localStorage.getItem(KEY+"_session");
const seeds=[
{id:"p1",userId:"u1",name:"Ishita Sharma",username:"ishita07",title:"Is our education system preparing us for real life?",body:"We memorise for exams, not for understanding. We compete for marks, not for growth.\n\nIt is time we rethink what success really means.",topic:"Education",tags:["education","youth"],createdAt:Date.now()-7200000,likes:1200,likedBy:[],savedBy:[],comments:[]},
{id:"p2",userId:"u2",name:"Raghav Mehta",username:"raghavwrites",title:"We need better spaces for disagreement.",body:"A healthy debate is not about winning. It is about leaving the conversation with a better understanding of the other side.",topic:"Society",tags:["society","debates"],createdAt:Date.now()-15000000,likes:730,likedBy:[],savedBy:[],comments:[]},
{id:"p3",userId:"u3",name:"Mehak Verma",username:"mehakwrites",title:"What should colleges teach that textbooks do not?",body:"Money, communication, basic law, digital safety and critical thinking should not be optional life lessons.",topic:"Campus",tags:["campus","education","india"],createdAt:Date.now()-28000000,likes:482,likedBy:[],savedBy:[],comments:[]},
{id:"p4",userId:"u4",name:"Arjun Nair",username:"arjunn",title:"Your first job is not supposed to be your final identity.",body:"We put too much pressure on young people to choose one path at 20. Careers change. Skills compound. Learning should matter more than a perfect first decision.",topic:"Careers",tags:["careers","youngindia"],createdAt:Date.now()-40000000,likes:341,likedBy:[],savedBy:[],comments:[]}
];
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));return x&&x.users?x:{users:[],posts:seeds,notifications:[]}}catch{return{users:[],posts:seeds,notifications:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function user(){return db.users.find(x=>x.id===session)||null}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function ago(t){let m=Math.max(1,Math.floor((Date.now()-t)/60000));if(m<60)return m+"m";let h=Math.floor(m/60);if(h<24)return h+"h";return Math.floor(h/24)+"d"}
function toast(s){let n=document.getElementById("toast");n.textContent=s;n.classList.add("show");setTimeout(()=>n.classList.remove("show"),1800)}
function initials(name){return (name||"Q").split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()}
function ensureUser(){if(user())return;let d={id:"demo",name:"Demo User",username:"demo_user",email:"demo@qavrin.in",password:"qavrin123",bio:"Here to read, think and write."};if(!db.users.length)db.users.push(d);session=db.users[0].id;save()}
function renderIdentity(){let u=user();if(!u)return;document.getElementById("sideName").textContent=u.name;document.getElementById("sideHandle").textContent="@"+u.username;document.getElementById("sideAvatar").textContent=initials(u.name);document.getElementById("profileAvatar").textContent=initials(u.name);document.getElementById("profileName").textContent=u.name;document.getElementById("profileHandle").textContent="@"+u.username;document.getElementById("profileBio").textContent=u.bio||"Your voice. Your perspective.";document.getElementById("composerAvatar").textContent=initials(u.name);document.getElementById("composerName").textContent=u.name}
function postHTML(p){let u=user(),liked=p.likedBy?.includes(u?.id),saved=p.savedBy?.includes(u?.id),comments=p.comments||[];return `<article class="post" data-id="${p.id}"><div class="post-top"><div class="post-author"><div class="avatar-letter">${esc(initials(p.name))}</div><div><strong>${esc(p.name)}</strong><span>@${esc(p.username)} · ${ago(p.createdAt)}</span></div></div><span class="topic">${esc(p.topic)}</span></div><h3>${esc(p.title)}</h3><div class="post-body">${esc(p.body)}</div>${p.tags?.length?`<div class="tags">${p.tags.map(x=>`<span>#${esc(x)}</span>`).join("")}</div>`:""}<div class="post-actions"><button class="action ${liked?"active":""}" data-a="like">♥ ${p.likes}</button><button class="action" data-a="comments">◯ ${comments.length}</button><button class="action ${saved?"active":""}" data-a="save">◇ ${saved?"Saved":"Save"}</button>${p.userId===u?.id?`<button class="action" data-a="delete">Delete</button>`:""}</div><div class="comment-box"><input maxlength="180" placeholder="Add a comment"><button data-a="send">Send</button></div>${comments.slice(-4).map(c=>`<div class="comments"><div class="comment"><b>${esc(c.name)}</b> · @${esc(c.username)}<br>${esc(c.text)}</div></div>`).join("")}</article>`}
function getPosts(){let q=(document.getElementById("searchInput")?.value||"").toLowerCase(),topic=document.getElementById("topicFilter")?.value||"all",sort=document.querySelector(".seg.active")?.dataset.sort||"latest";let a=[...db.posts];if(q)a=a.filter(p=>(p.title+" "+p.body+" "+p.name+" "+p.username+" "+p.tags.join(" ")).toLowerCase().includes(q));if(topic!=="all")a=a.filter(p=>p.topic===topic);if(sort==="popular")a.sort((x,y)=>y.likes-x.likes);else a.sort((x,y)=>y.createdAt-x.createdAt);return a}
function renderFeed(target="feed",posts=getPosts()){let n=document.getElementById(target);if(!n)return;n.innerHTML=posts.length?posts.map(postHTML).join(""):`<div class="post"><strong>No thoughts found.</strong><p class="muted">Try another search or topic.</p></div>`}
function switchView(view){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));document.getElementById(view+"View").classList.remove("hidden");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));let titles={home:["YOUR FEED","Thoughts worth reading."],explore:["EXPLORE","Find a conversation."],notifications:["NOTIFICATIONS","Stay in the loop."],profile:["PROFILE","Your QAVRIN."],saved:["SAVED","Things worth revisiting."]};document.getElementById("viewOverline").textContent=titles[view][0];document.getElementById("viewTitle").textContent=titles[view][1];if(view==="home")renderFeed();if(view==="explore")renderExplore();if(view==="notifications")renderNotifications();if(view==="profile")renderProfile();if(view==="saved")renderSaved();document.getElementById("sidebar").classList.remove("open")}
function openModal(id){document.getElementById(id).classList.remove("hidden")}
function closeModal(id){document.getElementById(id).classList.add("hidden")}
function renderExplore(){let counts={};db.posts.forEach(p=>counts[p.topic]=(counts[p.topic]||0)+1);document.getElementById("topicGrid").innerHTML=["India","Education","Careers","Campus","Technology","Society","Debates","General"].map(t=>`<button class="topic-tile" data-topic-tile="${t}"><strong>${t}</strong><span>${counts[t]||0} conversations</span></button>`).join("");renderFeed("exploreFeed",[...db.posts].sort((a,b)=>b.likes-a.likes))}
function renderNotifications(){let n=document.getElementById("notificationsList");let arr=db.notifications.length?db.notifications:[{text:"Welcome to QAVRIN. This is your notifications space.",time:"now",read:false},{text:"Start by writing your first thought.",time:"now",read:false},{text:"Explore topics to find people you want to read.",time:"now",read:false}];n.innerHTML=arr.map(x=>`<div class="notification ${x.read?"":"unread"}"><div class="mini-avatar">Q</div><div><strong>${esc(x.text)}</strong><span>QAVRIN</span></div><time>${esc(x.time)}</time></div>`).join("")}
function renderProfile(){let u=user();let mine=db.posts.filter(p=>p.userId===u.id);document.getElementById("statPosts").textContent=mine.length;document.getElementById("statFollowers").textContent="0";document.getElementById("statFollowing").textContent="0";renderFeed("profileFeed",mine)}
function renderSaved(){let u=user();renderFeed("savedFeed",db.posts.filter(p=>p.savedBy?.includes(u.id)))}
function publish(){let u=user();if(!u){openModal("authModal");return}let title=document.getElementById("postTitle").value.trim(),body=document.getElementById("postBody").value.trim();if(title.length<4)return toast("Add a clear title.");if(body.length<20)return toast("Write a little more.");let tags=document.getElementById("postTags").value.split(",").map(x=>x.trim().replace(/^#/,"")).filter(Boolean).slice(0,6);db.posts.unshift({id:crypto.randomUUID(),userId:u.id,name:u.name,username:u.username,title,body,topic:document.getElementById("postTopic").value,tags,createdAt:Date.now(),likes:0,likedBy:[],savedBy:[],comments:[]});save();["postTitle","postBody","postTags"].forEach(id=>document.getElementById(id).value="");document.getElementById("postCount").textContent="0/1500";closeModal("composerModal");renderFeed();toast("Published.");}
function authMode(mode){document.querySelectorAll(".auth-tab").forEach(x=>x.classList.toggle("active",x.dataset.auth===mode));document.getElementById("loginForm").classList.toggle("hidden",mode!=="login");document.getElementById("signupForm").classList.toggle("hidden",mode!=="signup")}
function login(e){e.preventDefault();let email=document.getElementById("loginEmail").value.trim().toLowerCase(),pass=document.getElementById("loginPassword").value,u=db.users.find(x=>x.email===email&&x.password===pass);if(!u)return toast("Email or password is incorrect.");session=u.id;localStorage.setItem(KEY+"_session",session);closeModal("authModal");renderIdentity();toast("Welcome back.");}
function signup(e){e.preventDefault();let name=document.getElementById("signupName").value.trim(),username=document.getElementById("signupUsername").value.trim().toLowerCase(),email=document.getElementById("signupEmail").value.trim().toLowerCase(),pass=document.getElementById("signupPassword").value;if(db.users.some(x=>x.email===email))return toast("Email already registered.");if(db.users.some(x=>x.username===username))return toast("Username already taken.");let u={id:crypto.randomUUID(),name,username,email,password:pass,bio:""};db.users.push(u);session=u.id;localStorage.setItem(KEY+"_session",session);save();closeModal("authModal");renderIdentity();toast("Account created.");}
document.querySelectorAll(".nav-item").forEach(x=>x.onclick=()=>switchView(x.dataset.view));
document.querySelectorAll(".topic-nav button").forEach(x=>x.onclick=()=>{document.getElementById("topicFilter").value=x.dataset.topic;switchView("home")});
document.getElementById("openComposer").onclick=()=>user()?openModal("composerModal"):openModal("authModal");
document.getElementById("headerCompose").onclick=()=>user()?openModal("composerModal"):openModal("authModal");
document.getElementById("bannerWrite").onclick=()=>user()?openModal("composerModal"):openModal("authModal");
document.getElementById("publish").onclick=publish;
document.getElementById("searchInput").oninput=()=>renderFeed();
document.getElementById("topicFilter").onchange=()=>renderFeed();
document.querySelectorAll(".seg").forEach(x=>x.onclick=()=>{document.querySelectorAll(".seg").forEach(y=>y.classList.remove("active"));x.classList.add("active");renderFeed()});
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>closeModal(x.dataset.close));
document.querySelectorAll(".auth-tab").forEach(x=>x.onclick=()=>authMode(x.dataset.auth));
document.getElementById("loginForm").onsubmit=login;document.getElementById("signupForm").onsubmit=signup;
document.getElementById("demoLogin").onclick=()=>{ensureUser();localStorage.setItem(KEY+"_session",session);closeModal("authModal");renderIdentity();toast("Signed in.")};
document.getElementById("logoutBtn")?.addEventListener("click",()=>{session=null;localStorage.removeItem(KEY+"_session");location.reload()});
document.getElementById("accountButton").onclick=()=>switchView("profile");
document.getElementById("mobileMenu").onclick=()=>document.getElementById("sidebar").classList.toggle("open");
document.getElementById("mobileSearch").onclick=()=>document.getElementById("searchInput").focus();
document.getElementById("postBody").oninput=e=>document.getElementById("postCount").textContent=e.target.value.length+"/1500";
document.getElementById("feed").onclick=handlePostAction;document.getElementById("exploreFeed").onclick=handlePostAction;document.getElementById("profileFeed").onclick=handlePostAction;document.getElementById("savedFeed").onclick=handlePostAction;
function handlePostAction(e){let card=e.target.closest(".post");if(!card)return;let p=db.posts.find(x=>x.id===card.dataset.id),u=user(),a=e.target.closest("[data-a]")?.dataset.a;if(!p||!u)return;if(a==="like"){p.likedBy=p.likedBy||[];let i=p.likedBy.indexOf(u.id);if(i>=0){p.likedBy.splice(i,1);p.likes--}else{p.likedBy.push(u.id);p.likes++}save();renderFeed(card.closest("#profileFeed")?"profileFeed":card.closest("#savedFeed")?"savedFeed":"feed")}
if(a==="save"){p.savedBy=p.savedBy||[];let i=p.savedBy.indexOf(u.id);if(i>=0)p.savedBy.splice(i,1);else p.savedBy.push(u.id);save();toast(i>=0?"Removed from saved":"Saved");renderFeed(card.closest("#savedFeed")?"savedFeed":"feed")}
if(a==="delete"){db.posts=db.posts.filter(x=>x.id!==p.id);save();renderFeed();toast("Post deleted.")}
if(a==="comments"){card.querySelector(".comment-box").classList.toggle("hidden")}
if(a==="send"){let input=card.querySelector(".comment-box input"),text=input.value.trim();if(!text)return;p.comments=p.comments||[];p.comments.push({name:u.name,username:u.username,text});save();renderFeed();toast("Comment added.")}
}
document.getElementById("editProfile").onclick=()=>{let u=user();document.getElementById("editName").value=u.name;document.getElementById("editBio").value=u.bio||"";openModal("editModal")};
document.getElementById("editForm").onsubmit=e=>{e.preventDefault();let u=user();u.name=document.getElementById("editName").value.trim();u.bio=document.getElementById("editBio").value.trim();save();renderIdentity();closeModal("editModal");toast("Profile updated.")};
document.getElementById("markRead").onclick=()=>{db.notifications.forEach(x=>x.read=true);save();renderNotifications();document.getElementById("notificationBadge").textContent="0"};
document.getElementById("exploreSearch").oninput=e=>{let q=e.target.value.toLowerCase();renderFeed("exploreFeed",db.posts.filter(p=>(p.title+" "+p.body+" "+p.name+" "+p.tags.join(" ")).toLowerCase().includes(q)))};
document.getElementById("topicGrid").onclick=e=>{let t=e.target.closest("[data-topic-tile]")?.dataset.topicTile;if(t){document.getElementById("topicFilter").value=t;switchView("home")}};
document.querySelectorAll(".person button").forEach(b=>b.onclick=()=>{b.textContent=b.textContent==="Follow"?"Following":"Follow";toast(b.textContent==="Following"?"Following":"Unfollowed")});
if(!db.users.length){db.users.push({id:"demo",name:"Demo User",username:"demo_user",email:"demo@qavrin.in",password:"qavrin123",bio:"Here to read, think and write."});save()}
if(session&&!user())session=null;
renderIdentity();renderFeed();renderNotifications();
